package Modelo;

public enum GameGenre {
	ACCION, ACCION_Y_AVENTURA, LUCHA, SIGILO, FIRST_PERSON_SHOOTER, THIRD_PERSON_SHOOTER, RPG, MMO,
	ESTRATEGIA_POR_TURNOS, ESTRATEGIA_EN_TIEMPO_REAL, MOBA, AVENTURA, NOVELA_VISUAL, TERROR, PLATAFORMAS, SUPERVIVENCIA,
	ARCADE, CARTAS, DEPORTES, SIMULACIÓN, PARTY, PUZLES, MUSICAL
}
